---
title: "Day 4 Interactive"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

## More functions

Create a subset within a function, and then return something based on that subset.

```{r}

dog_choice <- data.frame(dog_name = c("a", "b", "c", "d", "e"),
                         food = c("all", "salmon", "pans", "chicks", "dudes"))
```

Make a function

```{r}
dog_menu <- function(enter_dog_name) {
  selected_dog <- filter(dog_choice, dog_name == enter_dog_name) # create subset to create input row
  print(paste("My name is", selected_dog$dog_name))
}

dog_menu("d")
```

## Function with a for loop

Plan:

-   iterate over each column

-   calculate mean value for each column

-   store them

```{r}
df_means <- function(df) {
  for (i in seq_along(df)) {
    col_mean <- round(mean(df[[i]], na.rm = TRUE)) # return rounded MEANS of the vector of values [[]] from the column 
    column_name <- colnames(df[i]) # access column name of selected column i
    print(paste("The mean value of", column_name, "is", col_mean))
  }
}

df <- mtcars

df_means(mtcars)
```
